if(NOT DEFINED RAYLIB_SOURCE_DIR)
    message(FATAL_ERROR "RAYLIB_SOURCE_DIR is required")
endif()
set(raylib_cmake "${RAYLIB_SOURCE_DIR}/CMakeLists.txt")
file(READ "${raylib_cmake}" contents)
if(contents MATCHES "project\\(raylib LANGUAGES C\\)")
    return()
endif()
string(FIND "${contents}" "project(raylib)" match)
if(match EQUAL -1)
    message(FATAL_ERROR "Pinned raylib root project() differs; review before updating this patch")
endif()
string(REPLACE "project(raylib)" "project(raylib LANGUAGES C)" contents "${contents}")
file(WRITE "${raylib_cmake}" "${contents}")
